# Generated by Django 4.1.6 on 2023-02-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='description',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
